// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjyRsfmsPJdwOlohtfsYUrA9eqVEWhjW4',
    appId: '1:323043528214:web:b0f462560bd88b4e642f37',
    messagingSenderId: '323043528214',
    projectId: 'tyed-app',
    authDomain: 'tyed-app.firebaseapp.com',
    storageBucket: 'tyed-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ke4iTQu6CJPHy2e1tRvo8JcB65XyCvY',
    appId: '1:323043528214:android:506bad48d4d8957b642f37',
    messagingSenderId: '323043528214',
    projectId: 'tyed-app',
    storageBucket: 'tyed-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHgNx5lmPfZLnbhxhZldfqqt_CvVhIRs',
    appId: '1:323043528214:ios:e6047ce9c0463203642f37',
    messagingSenderId: '323043528214',
    projectId: 'tyed-app',
    storageBucket: 'tyed-app.appspot.com',
    iosBundleId: 'com.example.tyedapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHgNx5lmPfZLnbhxhZldfqqt_CvVhIRs',
    appId: '1:323043528214:ios:8783ac96f595a770642f37',
    messagingSenderId: '323043528214',
    projectId: 'tyed-app',
    storageBucket: 'tyed-app.appspot.com',
    iosBundleId: 'com.example.tyedapp.RunnerTests',
  );
}
